export default function SampleReport() {
    return (
        <section className="py-[80px] border-t border-white/5 bg-[#050505]" id="sample-report">
            <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-16">
                    <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4 leading-tight">
                        See a Real Trading Edge Report
                    </h2>
                    <p className="text-base text-gray-400 max-w-xl mx-auto">
                        Explore an example of the quantitative report generated by NodoQuant.
                    </p>
                </div>

                <div className="max-w-4xl mx-auto bg-black/40 border border-white/10 rounded-2xl p-6 sm:p-10 shadow-2xl backdrop-blur-sm relative overflow-hidden group">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-indigo-500 opacity-50" />

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
                        {/* Score Preview */}
                        <div className="col-span-1 flex flex-col justify-center items-center p-8 bg-white/5 rounded-2xl border border-white/10 shadow-xl relative overflow-hidden group-hover:border-indigo-500/30 transition-all">
                            <div className="absolute top-0 right-0 w-12 h-12 bg-white/5 rounded-bl-full" />
                            <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest mb-1">Strategy Score</span>
                            <div className="flex items-baseline gap-1">
                                <span className="text-6xl font-black text-emerald-400">82</span>
                                <span className="text-sm font-bold text-emerald-400/30">/ 100</span>
                            </div>
                            <span className="text-[10px] font-black text-emerald-400 uppercase tracking-[0.2em] mt-3 py-1 px-3 bg-emerald-400/10 rounded-lg">Strong Edge</span>
                        </div>

                        {/* Metrics Preview */}
                        <div className="col-span-1 md:col-span-2 grid grid-cols-2 gap-4">
                            {[
                                { label: "Win Rate", value: "45.2%", color: "text-white" },
                                { label: "Profit Factor", value: "1.84", color: "text-white" },
                                { label: "Expectancy", value: "0.42 R", color: "text-emerald-400" },
                                { label: "Max Drawdown", value: "-12.5%", color: "text-red-400" },
                            ].map((m) => (
                                <div key={m.label} className="p-4 bg-white/5 rounded-xl border border-white/5 flex flex-col justify-center">
                                    <span className="text-gray-500 text-[10px] font-black uppercase tracking-widest mb-1">{m.label}</span>
                                    <span className={`text-xl font-bold ${m.color}`}>{m.value}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Equity Curve Fake Graphic */}
                    <div className="w-full h-48 bg-white/5 rounded-xl border border-white/5 p-5 relative overflow-hidden flex flex-col justify-end">
                        <span className="absolute top-4 left-4 text-xs font-medium text-gray-500 uppercase tracking-widest">Equity Curve</span>
                        <svg className="w-full h-full opacity-70 mt-6" preserveAspectRatio="none" viewBox="0 0 100 40">
                            <defs>
                                <linearGradient id="eq-grad" x1="0" y1="0" x2="0" y2="1">
                                    <stop offset="0%" stopColor="#818cf8" stopOpacity="0.4" />
                                    <stop offset="100%" stopColor="#818cf8" stopOpacity="0" />
                                </linearGradient>
                            </defs>
                            <path d="M0 40 L0 30 L10 28 L20 32 L30 20 L40 25 L50 15 L60 12 L70 20 L80 8 L90 5 L100 1 L100 40 Z" fill="url(#eq-grad)" />
                            <path d="M0 30 L10 28 L20 32 L30 20 L40 25 L50 15 L60 12 L70 20 L80 8 L90 5 L100 1" fill="none" stroke="#818cf8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                    </div>

                    <div className="mt-10 flex justify-center">
                        <a href="/report/example" className="btn-secondary py-3 px-8 bg-indigo-600/10 hover:bg-indigo-600/20 text-indigo-400 font-semibold rounded-lg transition-colors border border-indigo-500/20 group">
                            View Full Sample Report
                            <span className="inline-block transition-transform duration-200 group-hover:translate-x-1 ml-2">→</span>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    );
}
